### ISSUE TITLE
Modify the action for python test

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos-pypackage#1]
modifiy the action configuration file:

```yaml

on:
    push:
         - branches: [main]
```

to 

```yaml

on:
  push:
    branches:
    - '*'
```
